name: Static type check
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ./src/ruby/Gemfile
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: test_all
      run: BUNDLE_GEMFILE=Gemfile rake test_all
